image:
  repository: 849882217116.dkr.ecr.us-east-1.amazonaws.com/goit-ecr
  tag: latest
  pullPolicy: IfNotPresent

service:
  # type: ClusterIP
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false
