image:
  repository: 146115342990.dkr.ecr.us-east-1.amazonaws.com/goit-ecr
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  # type: ClusterIP
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false
  pullSecrets:
    - name: aws-ecr-creds
